/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RCN;

import javax.swing.JButton;

/**
 *
 * @author diego vidal
 */
public class Programa extends javax.swing.JFrame {

    /**
     * Creates new form TodoGamer2
     */
    public Programa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Boton_Superlike = new javax.swing.JButton();
        Boton_Programas1 = new javax.swing.JButton();
        Boton_Deportes = new javax.swing.JButton();
        Boton_Noticias = new javax.swing.JButton();
        Boton_TodoGamer = new javax.swing.JButton();
        Envivo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo2.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1028, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(1028, 768));
        jPanel1.setMinimumSize(new java.awt.Dimension(1028, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picasion.com_4a0d73ba99547b975b782aca0b9bd970.gif"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1335, 180));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo verde.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 9, -1, -1));

        Boton_Superlike.setBackground(new java.awt.Color(0, 0, 0));
        Boton_Superlike.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Boton_Superlike.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Superlike.setText("SuperLike");
        Boton_Superlike.setBorder(null);
        Boton_Superlike.setBorderPainted(false);
        Boton_Superlike.setOpaque(false);
        Boton_Superlike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_SuperlikeActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Superlike, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 36, -1, -1));

        Boton_Programas1.setBackground(new java.awt.Color(0, 0, 0));
        Boton_Programas1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Boton_Programas1.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Programas1.setText("Programas");
        Boton_Programas1.setBorder(null);
        Boton_Programas1.setBorderPainted(false);
        Boton_Programas1.setOpaque(false);
        Boton_Programas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Programas1ActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Programas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 36, -1, -1));

        Boton_Deportes.setBackground(new java.awt.Color(0, 0, 0));
        Boton_Deportes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Boton_Deportes.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Deportes.setText("Deportes");
        Boton_Deportes.setBorder(null);
        Boton_Deportes.setBorderPainted(false);
        Boton_Deportes.setOpaque(false);
        Boton_Deportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_DeportesActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Deportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 36, -1, -1));

        Boton_Noticias.setBackground(new java.awt.Color(0, 0, 0));
        Boton_Noticias.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Boton_Noticias.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Noticias.setText("Noticias");
        Boton_Noticias.setBorder(null);
        Boton_Noticias.setBorderPainted(false);
        Boton_Noticias.setOpaque(false);
        Boton_Noticias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_NoticiasActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Noticias, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 36, -1, -1));

        Boton_TodoGamer.setBackground(new java.awt.Color(0, 0, 0));
        Boton_TodoGamer.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Boton_TodoGamer.setForeground(new java.awt.Color(255, 255, 255));
        Boton_TodoGamer.setText("TodoGamers");
        Boton_TodoGamer.setBorder(null);
        Boton_TodoGamer.setBorderPainted(false);
        Boton_TodoGamer.setOpaque(false);
        Boton_TodoGamer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_TodoGamerActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_TodoGamer, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 36, -1, -1));

        Envivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/envivo.png"))); // NOI18N
        Envivo.setText("jLabel2");
        jPanel1.add(Envivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1031, 28, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gif1.gif"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 260, 143));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloggif_5dbf8a83b7a8b.gif"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, 270, 160));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloggif_5dbf8aab683a6.gif"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 540, 250, 140));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloggif_5dbf8ae8a28dc.gif"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 540, 220, 140));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo2.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 710, 1260, 250));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logos12.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 1260, 240));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -100, -1, 960));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_SuperlikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_SuperlikeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_SuperlikeActionPerformed

    private void Boton_Programas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Programas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_Programas1ActionPerformed

    private void Boton_DeportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_DeportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_DeportesActionPerformed

    private void Boton_NoticiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_NoticiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_NoticiasActionPerformed

    private void Boton_TodoGamerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_TodoGamerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_TodoGamerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JButton miBoton = new JButton();

            miBoton.setBackground(java.awt.Color.BLACK);
                new Programa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Deportes;
    private javax.swing.JButton Boton_Noticias;
    private javax.swing.JButton Boton_Programas1;
    private javax.swing.JButton Boton_Superlike;
    private javax.swing.JButton Boton_TodoGamer;
    private javax.swing.JLabel Envivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
